%YAML:1.0
---
model_type: PINHOLE
camera_name: camera
image_width: 640
image_height: 360
distortion_parameters:
   k1: 0
   k2: 0
   p1: 0
   p2: 0
projection_parameters:
   fx: 267.0543675596685
   fy: 267.43700734204106
   cx: 318.4184320150471
   cy: 183.12790104465248
